name: frifri
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # This will break flutter gen-l10n and all imports...
  # flutter_gen: any

  cupertino_icons: ^1.0.6
  go_router: ^13.2.4
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.6
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.5
  dio: ^5.4.3+1
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.9.0
  crypto: ^3.0.3
  logger: ^2.3.0
  equatable: ^2.0.5
  flutter_lints: ^4.0.0
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  build_runner: ^2.4.9
  lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icons/icon.png"

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - .env
